### ISSUE TITLE
Upgrade to Babel6

### ISSUE THREAD

**Issue by amcdnl** [chocolateboy/babel-plugin-source-map-support#2] opened 2015-12-21 15:34 UTC
Doen'st work with Babel6

**Comment by chocolateboy** [comment] 2015-12-21 15:36
Duplicate of #1.

**Closed by chocolateboy** 2015-12-21 15:36 UTC

**Comment by amcdnl** [comment] 2015-12-21 15:39
sorry ;)

**Comment by mykohsu** [comment] 2016-02-06 00:54
I get the following error with the commit. I also tried on the included test.js.

Executed `babel --plugins source-map-support test.js`

```
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at C:\Users\...\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:191:20
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\...\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\options\option-manager.js:173:20)
```
